### ISSUE TITLE
Uninstall didn't remove all trace

### ISSUE THREAD

**Issue by patakijv** [descala/haltr#54]
I just ran through the uninstall process of haltr 1.0 on redmine 1.2 as part of our migration process to a new redmine. I had to fix some of the migrations but managed to get it to the point where the migrations all rolled back. However, there are still traces of haltr in the redmine interface. I see it in the plugins list in administrative menu and its an option in the still in the modules section of our projects. What else needs to happen to get it all removed?

**Comment by patakijv** [comment]
Nevermind, my bad - I forgot to "restart" redmine. Now it is cleared.

**Comment by descala** [comment]
OK
