### ISSUE TITLE
error in customization saving

### ISSUE THREAD

**Issue by hojjatnikan** [descala/haltr#55]
Hi 
When i want to save customization i received following error :
App 29098 stderr: IndexError (string not matched):
App 29098 stderr:   plugins/haltr/app/models/company.rb:180:in `[]='
App 29098 stderr:   plugins/haltr/app/models/company.rb:180:in `invoice_mail_subject='
App 29098 stderr:   plugins/haltr/app/models/company.rb:293:in `public_send'
App 29098 stderr:   plugins/haltr/app/models/company.rb:293:in `method_missing'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/attribute_assignment.rb:85:in `block in assign_attributes'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/attribute_assignment.rb:78:in `each'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/persistence.rb:216:in `block in update_attributes'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/transactions.rb:208:in `transaction'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/persistence.rb:215:in `update_attributes'
App 29098 stderr:   plugins/haltr/app/controllers/companies_controller.rb:96:in `update'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
App 29098 stderr:   actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:514:in `block in _run__2818173665602237904__process_action__3122066178664072847__callbacks'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_3129'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:326:in `around'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:310:in `_callback_around_67'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_3129'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:414:in `_run__2818173665602237904__process_action__3122066178664072847__callbacks'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
App 29098 stderr:   actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
App 29098 stderr:   actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
App 29098 stderr:   actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
App 29098 stderr:   actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
App 29098 stderr:   journey (1.0.4) lib/journey/router.rb:68:in `block in call'
App 29098 stderr:   journey (1.0.4) lib/journey/router.rb:56:in `each'
App 29098 stderr:   journey (1.0.4) lib/journey/router.rb:56:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/routing
App 29098 stderr: /route_set.rb:608:in `call'
App 29098 stderr:   rack-raw-upload (1.1.1) lib/rack/raw_upload.rb:18:in `call'
App 29098 stderr:   rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
App 29098 stderr:   request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/etag.rb:23:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
App 29098 stderr:   plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
App 29098 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
App 29098 stderr:   activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__187184007501866700__call__1754290279975020815__callbacks'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
App 29098 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
App 29098 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
App 29098 stderr:   railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/runtime.rb:17:in `call'
App 29098 stderr:   activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
App 29098 stderr:   rack (1.4.5) lib/rack/lock.rb:15:in `call'
App 29098 stderr:   actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
App 29098 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
App 29098 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:143:in `pass'
App 29098 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
App 29098 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:71:in `call!'
App 29098 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
App 29098 stderr:   railties (3.2.21) lib/rails/engine.rb:484:in `call'
App 29098 stderr:   railties (3.2.21) lib/rails/application.rb:231:in `call'
App 29098 stderr:   railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
App 29098 stderr:   passenger (4.0.58) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 29098 stderr:   passenger (4.0.58) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 29098 stderr:   passenger (4.0.58) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 29098 stderr:   passenger (4.0.58) lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
App 29098 stderr:
App 29098 stderr:

**Comment by descala** [comment]
I hope this solves your issue
