### ISSUE TITLE
bug in exportable_document.rb

### ISSUE THREAD

**Issue by hojjatnikan** [descala/haltr#57]
the line number of error is 31 in file exportable_document.rb :
     if channel["format"] == "pdf" and self.client and self.client.language != User.current.language

i changed above line with following line (bug is solved)

if channel and channel["format"] == "pdf" and self.client and self.client.language != User.current.language

**Comment by descala** [comment]
The default channel is 'signed_pdf' and it was missing in channels.yml.example. This is the root cause that triggers this issue, but I have added your nil protection anyway. Thanks!
